### ISSUE TITLE
Form Assembly Technical Spike 

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/business-launchpad#14]
Answer the following questions:
- Can we connect our app with Form Assembly?
- How can we include a form on our page?
- How much can we control the style of a form?
- Is it worth it?

**Comment by SalwaMugh** [comment]
I found this , tonight I will be reading it https://github.com/veerwest/formassembly-api
click in the node to see how it work in nodejs.
also in the website https://www.formassembly.com
they offer a How it works & Getting started .
formassembly is a paid service , but they offer a free try at the footer of the website

**Comment by Oliversw** [comment]
Thanks Salwa!! We have a meeting with Naveen who works with Form Assembly at Business Launchpad on Wednesday, so hopefully she will help us to embed everything. I'll take a look at your links in the meantime!

**Comment by Oliversw** [comment]
Waiting to hear back from BL about whether we can use Form Assembly or not
