### ISSUE TITLE
Figma - figure out button consistency

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/business-launchpad#26]
Made some mock ups using the hamburger menu buttons, but I don't think it works for our needs. As the header styling comes straight from the organisation's branding, I think it should probably stay that way, but having it so similar to the buttons is a bit confusing. Thoughts?

Original:
![Screen Shot 2019-06-07 at 13 23 25](https://user-images.githubusercontent.com/37771591/59103872-ef1e9700-8927-11e9-83d0-43d47e31d5a8.png)

Some different mock ups:
![Screen Shot 2019-06-07 at 13 23 33](https://user-images.githubusercontent.com/37771591/59103803-bc749e80-8927-11e9-8137-cb7701f37e5c.png)
![Screen Shot 2019-06-07 at 13 45 37](https://user-images.githubusercontent.com/37771591/59104872-969cc900-892a-11e9-8f41-ddd034a81b10.png)
![Screen Shot 2019-06-07 at 13 45 43](https://user-images.githubusercontent.com/37771591/59104880-98ff2300-892a-11e9-88cc-b9b37d5bd4d6.png)

Another style:
![Screen Shot 2019-06-07 at 13 23 40](https://user-images.githubusercontent.com/37771591/59103808-c0a0bc00-8927-11e9-910e-5b8f0d194d1c.png)

**Comment by teenie-quaggard** [comment]
One other snap to consider

Original:

![Screen Shot 2019-06-07 at 15 34 26](https://user-images.githubusercontent.com/37771591/59111864-c99a8900-8939-11e9-86fb-bff9cf885f75.png)

New: 

![Screen Shot 2019-06-07 at 15 33 31](https://user-images.githubusercontent.com/37771591/59111824-b38cc880-8939-11e9-945d-5505f93c58ab.png)

**Comment by SalwaMugh** [comment]
I like the original buttons with the round edges , the other one Is HARSH

**Comment by shaima96** [comment]
For me, I like the original buttons.
we can put color border for the buttons maybe change the background color for the button, for example, put it black and border color is yellow and the font color is yellow.

I have a suggestion:
If we can make a blp icon as a button to return to the previous page?

**Comment by teenie-quaggard** [comment]
@SalwaMugh & @shaima96 - thanks! I agree with you about the buttons - this was just something that came from user feedback, but I think that since we all think otherwise, we can keep the originals :)
