### ISSUE TITLE
Create React context that wraps around all routed pages

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/business-launchpad#36]

**Comment by SalwaMugh** [comment]
@teenie-quaggard  What do you mean by that??!!

**Comment by teenie-quaggard** [comment]
@SalwaMugh context is another way of passing props around. It simplifies the process of passing props when an element is not a direct child of another.

For example, when two components are sibling component or if components are quite nested (example:  imagine these are components  - Grandfather -> Parent -> Child. In order to pass props from grandfather to child, we would need to pass props through parent even though parent isn't using those props. Context creates a 'global' store of props so that all of those components can access those props if they need it).

Here are the official docs:
https://reactjs.org/docs/context.html

Here is a repo where we used context in the past (with Ali!):
https://github.com/founders-programme-2/commons/tree/master/client/src

Wes Bos video on context:
https://www.youtube.com/watch?v=XLJN4JfniH4

Have a look at these and if you are still having trouble, we can pair tomorrow or I can set it up so that you can see how it works and then maybe use it on your next project! :) 

Hope that's useful!

**Comment by SalwaMugh** [comment]
thank you Kristina :heart:  I will be looking at it first thing in the morning.
