### ISSUE TITLE
Set up tests that each component loads

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/business-launchpad#37]

**Comment by shaima96** [comment]
@teenie-quaggard Can you add more description about this point, plz?

**Comment by teenie-quaggard** [comment]
@shaima96 So this was in the spirit of TDD!
I had it in our mind, that we would need to write a failing test that the component exists. And then we would create that component and our test would pass. 
I'm not actually sure how this would look though...maybe we don't need to make this initial test as it is too small and a waste of time.

@founders-programme-2/business-launchpad just a note on Jest / React testing 
https://jestjs.io/docs/en/tutorial-react

If we do any DOM testing we will probably use https://airbnb.io/enzyme/
which seems to be the biggest React testing library for mocking user interaction etc.

**Comment by shaima96** [comment]
I will do it using  https://airbnb.io/enzyme/ @teenie-quaggard 
Did you use it before?
