### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/business-launchpad#68]
- takes text and path as props
    - black or white (can be done with [styled components props](https://www.styled-components.com/docs/basics#adapting-based-on-props)

![Screen Shot 2019-06-10 at 5 48 36 PM](https://user-images.githubusercontent.com/9094166/59211553-07044e00-8ba8-11e9-8999-62c865c1c960.png)
![Screen Shot 2019-06-10 at 5 48 40 PM](https://user-images.githubusercontent.com/9094166/59211554-079ce480-8ba8-11e9-974a-80dc2d1a9f6b.png)
![Screen Shot 2019-06-10 at 5 48 48 PM](https://user-images.githubusercontent.com/9094166/59211555-079ce480-8ba8-11e9-9573-fc13f9f5ae20.png)

**Comment by shaima96** [comment]
Can explain more about this issue, please? @Oliversw

**Comment by Oliversw** [comment]
https://www.styled-components.com/docs/basics#adapting-based-on-props
