### ISSUE TITLE
Component: Resources

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/business-launchpad#72]
![Screen Shot 2019-06-10 at 5 32 38 PM](https://user-images.githubusercontent.com/9094166/59211759-91e54880-8ba8-11e9-9520-77f33a686ea1.png)

- accordion functionality that drops down on click
 - resource fields to be decided once we receive examples from Andria

**Comment by teenie-quaggard** [comment]
Quick note that the styling on this should emulate the /journal page
